# SPDX-License-Identifier: GPL-3.0-or-later
CC	= ee-gcc

CFLAGS	= -O3 -ffreestanding -std=c99 -I../include -G0 -Wall
ASFLAGS	= -I../include

FILES	= bootstrap.o gs.o mem.o start.o stdout.o thread.o

all: $(FILES)
